name: Build and Sync Frontend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Create version file
        run: |
          echo "{\"version\": \"1.0.0.${{ steps.date.outputs.date }}\", \"updated_at\": \"$(date +'%Y-%m-%d %H:%M:%S')\"}" > build/version.json

      - name: Checkout plugin repository
        uses: actions/checkout@v3
        with:
          repository: 789Abhi/CCC-Plugin
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: plugin-repo
          ref: Master

      - name: Clean assets directory
        run: |
          mkdir -p plugin-repo/assets
          rm -rf plugin-repo/assets/*

      - name: Copy build to plugin assets
        run: |
          cp -r build/* plugin-repo/assets/
          
      - name: Update plugin version
        run: |
          VERSION=$(cat build/version.json | jq -r .version)
          sed -i "s/Version: [0-9.]\+/Version: $VERSION/" plugin-repo/ccc-plugin.php
          sed -i "s/define( 'CCC_PLUGIN_VERSION', '[0-9.]\+' );/define( 'CCC_PLUGIN_VERSION', '$VERSION' );/" plugin-repo/ccc-plugin.php

      - name: Commit and push changes to plugin repo
        working-directory: ./plugin-repo
        run: |
          git config user.name "Abhishek"
          git config user.email "abhishektk18@gmail.com"
          git add .
          git commit -m "Update frontend assets to version from ${{ steps.date.outputs.date }}"
          git push origin Master